#!/sbin/runscript
# Copyright 2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header$

pidfile=${pidfile:-/run/${SVCNAME}.pid}
miner_config=${miner_config:-/etc/gszminer/${SVCNAME}.conf}
command="/usr/bin/gszminer"
command_args="--syslog -l 60 -q -c ${miner_config} ${miner_args}"
start_stop_daemon_args="-bm -N ${NICELEVEL:-20}"

depend() {
    need net
}

# check config!
# start_pre() {
# }
